import type { NextPage } from 'next';
import Head from 'next/head';
import React, { Fragment } from 'react';
import { CategoriesList } from '../components';

const Home: NextPage = () => (
  <Fragment>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <section className="market-section">
      <h1 className="market-section__h1-title text-center text-5xl font-bold mb-10">
        Market Place
      </h1>

      <CategoriesList />

      <div className="items-grid-wrapper">
        {[1, 2, 3, 4, 5].map((item) => (
          <a className="items-grid-wrapper__item" href="/" key={item}>
            <img className="items-grid-wrapper__item__img" height="100%" width="100%" src={`https://picsum.photos/200/300?random=${item}`} alt="" />

            <div className="items-grid-wrapper__item__content">
              <h5 className="font-bold mb-4">Gamer NFT</h5>

              <p className="items-grid-wrapper__item__content__p">The blahd of doin ewoiureio doeinioiei osuwieho odaishero sineohr oniwerionoihoehzzzz</p>
            </div>
          </a>
        ))}
      </div>
    </section>
  </Fragment>

);

export default Home;
