import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { Fragment, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { CategoriesList } from '../components';
import { action, selector } from '../redux/entities/collections';
import { CollectionType } from '../utils';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const router = useRouter();

  const { data } = useSelector((state: any) => selector(state));

  useEffect(() => {
    dispatch(action.readAction({ query: '?category=top' }).loading);
  }, [dispatch]);

  useEffect(() => {
    if (typeof router.query.tab === 'string') {
      dispatch(action.readAction({ query: `?category=${router.query.tab}` }).loading);
    }
  }, [dispatch, router.query]);

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="market-section">
        <h1 className="market-section__h1-title text-center text-5xl font-bold mb-10">
          Market Place
        </h1>

        <CategoriesList />

        <div className="items-grid-wrapper">
          {data.map((item: CollectionType) => {
            if (typeof item !== 'string' && typeof item.node !== 'number') {
              return (
                <a className="items-grid-wrapper__item" href="/" key={item.cursor}>
                  <img className="items-grid-wrapper__item__img" height="100%" width="100%" src={item.node.banner} alt="" />

                  <div className="items-grid-wrapper__item__content">
                    <div className="flex justify-center items-center mb-4">
                      <h5 className="items-grid-wrapper__item__content__h5 font-bold">{item.node.name || 'Unknown'}</h5>

                      <img src="/imgs/verified.png" alt="verified" height={18} width={18} />
                    </div>

                    <p className="items-grid-wrapper__item__content__p">{item.node?.description || ''}</p>
                  </div>
                </a>
              );
            }

            return null;
          })}
        </div>
      </section>
    </Fragment>
  );
};

export default Home;
