import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { Fragment, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';

import { CategoriesList, NftCard } from '../components';
import { action, selector } from '../redux/entities/collections';
import { CollectionType } from '../utils';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const router = useRouter();

  const { data } = useSelector((state: any) => selector(state));

  useEffect(() => {
    dispatch(action.readAction({ query: '?category=top' }).loading);
  }, [dispatch]);

  useEffect(() => {
    if (typeof router.query.tab === 'string') {
      dispatch(action.readAction({ query: `?category=${router.query.tab}` }).loading);
    }
  }, [dispatch, router.query]);

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="market-section">
        <h1 className="market-section__h1-title text-center text-3xl lg:text-5xl xl:text-7xl font-bold mb-10">
          Market Place
        </h1>

        <CategoriesList />

        <div className="items-grid-wrapper">
          {data.map((item: CollectionType) => {
            if (typeof item === 'object' && typeof item.node === 'object') {
              return <NftCard item={item} key={item.node.id} />;
            }

            return null;
          })}
        </div>
      </section>
    </Fragment>
  );
};

export default Home;
